name: Test the project

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4.1.2
       - uses: actions/setup-node@v4.0.2
       - run: yarn install
       - name: runs tests
         run: yarn test
